name: Build and Release

on:
  push:
    branches: ["master"]
    tags:
      - 'v*'
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            generator: "Visual Studio 17 2022"
            is_windows: true

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.24'

      - name: Configure CMake (Windows)
        if: matrix.is_windows
        shell: cmd
        run: |
          cmake -B build ^
            -G "${{ matrix.generator }}" ^
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} ^
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} ^
            -DCROW_FEATURES="asio"

      - name: Build (Windows)
        if: matrix.is_windows
        shell: cmd
        run: |
          cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Package (Windows)
        if: matrix.is_windows
        shell: cmd
        run: |
          cmake --build build --target package --config ${{ matrix.build_type }}
          dir build\

      - name: Upload artifacts (Windows)
        if: matrix.is_windows
        uses: actions/upload-artifact@v4
        with:
          name: Diabetes-server-Windows
          path: build/*.zip
